### ISSUE TITLE
Create 'Explain' function to relate generated proposition numbers back to conceptual propositions

### ISSUE THREAD

**Issue by wouterjsmit** [Pathemeous/Symbolic-Gossip#2]
Propositions generated have a semi-arbitrary numbering. It is not immediately obvious what each proposition stands for, making it hard to reason about the visualisations and output.

**Comment by wouterjsmit** [comment]
Relevant comment made here by @mgignoux 
https://github.com/Pathemeous/Symbolic-Gossip/commit/25c2e8ab6c5ea5cb6d3079e956e8c1265bb607e3#commitcomment-142141516

> I added a parameter for number of agents, so you can modulo that, but I think we need to change "thisCallProp" in Malvin's code because he uses 10, but we should change that 10 to the number of agents. So this code is not working yet because we also need to change Malvin's file. Or we can just assume <10 agents.

**Comment by wouterjsmit** [comment]
Replying to @mgignoux: I think there are also propositions offset with 100. It seems that this ams to create disjoint sets (some in the 10-99 range, some in the 100+ range). Maybe that clarifies the use of 10 in the original codebase.

**Comment by Zjoris** [comment]
In what kind of format do we want the output of explanations? A string that given a call/secret/Knowledge structure, tells you what everything means? Or is it an option to create a new type secretProp :: S Int Int and CallProp :: Q Int Int that we can put into a knowledge structure.
Or both? Haha

**Comment by Zjoris** [comment]
Also something seems off with GossipInit.

If I do GossipInit 5 I get

(KnS [P 1,P 2,P 3,P 4,P 5,P 7,P 8,P 9,P 10,P 11,P 13,P 14,P 15,P 16,P 17,P 19,P 20,P 21,P 22,P 23] Var 1 Bot (Var 2 Bot (Var 3 Bot (Var 4 Bot (Var 5 Bot (Var 7 Bot (Var 8 Bot (Var 9 Bot (Var 10 Bot (Var 11 Bot (Var 13 Bot (Var 14 Bot (Var 15 Bot (Var 16 Bot (Var 17 Bot (Var 19 Bot (Var 20 Bot (Var 21 Bot (Var 22 Bot (Var 23 Bot Top))))))))))))))))))) [("0",[]),("1",[]),("2",[]),("3",[]),("4",[])],[])

If I understand correctly the vocab [P 1,P 2,P 3,P 4,P 5,P 7,P 8,P 9,P 10,P 11,P 13,P 14,P 15,P 16,P 17,P 19,P 20,P 21,P 22,P 23] is missing a lot of propositions

**Comment by Zjoris** [comment]
So Explain now works for the initial model. But when using doCall to do an update on the initial model the vocabulary gets a couple of propositions that I do not know how to interpret. 
Since we are going to use a different update that makes different proposition I will wait with the rest of explain until the new transformer is further specified.

**Comment by m4lvin** [comment]
Maybe this helps to clarify a bit: Indeed the 100.. is to ensure disjoint sets, but mostly for human readability. The `update` function also uses `shiftPrepare` from [here](https://github.com/jrclogic/SMCDEL/blob/master/src/SMCDEL/Symbolic/S5.hs#L465) to ensure V+ is disjoint from V before actually applying the transformer. In the case of the call transformer it actually shifts down 100 to max(V)+1, 101 to max(V)+2 etc.

As for the explain function, I think it should only explain the basic vocabulary who knows which secret, i.e. the original V, and not even try to explain the additionally added atoms after an update (which may also disappear again if you use `optimize`).

**Comment by wouterjsmit** [comment]
Closed and completed.
